In [1]:
import numpy as np

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
np.arange(0,10)
arr= np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
np.zeros((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones((3,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [13]:
np.linspace(0,8,80)

array([0.        , 0.10126582, 0.20253165, 0.30379747, 0.40506329,
       0.50632911, 0.60759494, 0.70886076, 0.81012658, 0.91139241,
       1.01265823, 1.11392405, 1.21518987, 1.3164557 , 1.41772152,
       1.51898734, 1.62025316, 1.72151899, 1.82278481, 1.92405063,
       2.02531646, 2.12658228, 2.2278481 , 2.32911392, 2.43037975,
       2.53164557, 2.63291139, 2.73417722, 2.83544304, 2.93670886,
       3.03797468, 3.13924051, 3.24050633, 3.34177215, 3.44303797,
       3.5443038 , 3.64556962, 3.74683544, 3.84810127, 3.94936709,
       4.05063291, 4.15189873, 4.25316456, 4.35443038, 4.4556962 ,
       4.55696203, 4.65822785, 4.75949367, 4.86075949, 4.96202532,
       5.06329114, 5.16455696, 5.26582278, 5.36708861, 5.46835443,
       5.56962025, 5.67088608, 5.7721519 , 5.87341772, 5.97468354,
       6.07594937, 6.17721519, 6.27848101, 6.37974684, 6.48101266,
       6.58227848, 6.6835443 , 6.78481013, 6.88607595, 6.98734177,
       7.08860759, 7.18987342, 7.29113924, 7.39240506, 7.49367

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.rand()

0.3958251300684069

In [22]:
np.random.rand(4)

array([0.8291912 , 0.95922348, 0.12074214, 0.49701898])

In [23]:
np.random.rand(4,5)

array([[0.98178752, 0.02768933, 0.58524432, 0.34234022, 0.77196382],
       [0.29258012, 0.30074839, 0.35322989, 0.66259665, 0.4622845 ],
       [0.36521792, 0.23330386, 0.48115361, 0.12398243, 0.36631767],
       [0.58315652, 0.80042846, 0.00520389, 0.25689502, 0.92114768]])

In [31]:
np.random.randint(2,20)

12

*Aquí se esta generando numeros aleatorios entre 1 y 100 donde lo organiza en una matriz de 10x10.*

In [32]:
np.random.randint(1,100,(10,10))

array([[63, 22, 45, 78, 92,  5,  7, 95, 84, 14],
       [34, 84, 65, 75, 31,  5, 20,  3, 64, 54],
       [61, 91, 55, 76, 10, 30, 35, 11, 51, 74],
       [51, 57, 87, 80,  1, 95, 88, 14, 76, 58],
       [35,  3, 26, 53, 75, 84, 25, 48, 20, 55],
       [50, 78, 44, 90, 42, 64, 29,  8, 89, 91],
       [27, 70, 50, 59, 84, 27, 51,  2, 90, 84],
       [36,  2, 24, 42, 29, 66, 27, 65, 76, 21],
       [42, 48, 61, 29, 67, 72, 44, 56, 38, 98],
       [91, 63, 48, 50, 69, 95, 91, 60, 35, 26]])