In [1]:
import numpy as np

In [4]:
scalar = np.array(42)
scalar

array(42)

In [5]:
print(scalar)

42


In [6]:
scalar.ndim

0

***Declarando un vector***

In [9]:
vector = np.array([0,1,2,3,4])
print(vector)
vector.ndim

[0 1 2 3 4]


1

***Declarando una matriz***

In [13]:
matriz = np.array([[0,1, 2, 3], [4, 5, 6,7]])
print(matriz)
matriz.ndim

[[0 1 2 3]
 [4 5 6 7]]


2

In [14]:
matriz = np.array([[0,1, 2, 3], [4, 5, 6,7], [8,9,11,12]])
print(matriz)
matriz.ndim

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 11 12]]


2

***Declarando un tensor***

In [15]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],[[13, 13, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 13 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


3

*Agregar o eliminar dimensiones*

In [16]:
vector = np.array([1, 2, 3], ndmin = 10)
print(vector) 
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [25]:
vector_1 = vector = np.array([1, 2, 3], ndmin = 5)
print(vector_1) 
vector_1.ndim

[[[[[1 2 3]]]]]


5

*Ahora vamos a expandir nuestra array.*

In [17]:
np.expand_dims(np.array([1,2,3]),axis=0)

array([[1, 2, 3]])

In [20]:
expand = np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

Aquí estamos eliminando un vector.

In [21]:
print(vector, vector.ndim) 
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


In [26]:
print(vector_1, vector_1.ndim) 
vector_3 = np.squeeze(vector_1)
print(vector_3, vector_3.ndim)

[[[[[1 2 3]]]]] 5
[1 2 3] 1
