In [ ]:
print("Hola Otalvaro")

Hola Otalvaro


In [1]:
import numpy as np

In [4]:
list = [1,2,3,4,5,6,7,8,9]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
np.array(list)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr = np.array(list)

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[3]

4

In [14]:
arr[2]+arr[6]

10

In [15]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
matriz[2]

array([7, 8, 9])

In [19]:
matriz[1,1]

5

In [21]:
matriz[[1],[1]]

array([5])

In [22]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[1:5]

array([2, 3, 4, 5])

In [24]:
arr[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [26]:
arr[1:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr[::2]

array([1, 3, 5, 7, 9])

In [29]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
matriz[0:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [34]:
matriz[0:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [36]:
matriz[0:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])