In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,(3,2))
arr.shape

(3, 2)

In [3]:
arr.reshape(1,6)

array([[7, 3, 7, 1, 2, 8]])

In [4]:
arr.reshape(2,3)

array([[7, 3, 7],
       [1, 2, 8]])

In [5]:
np.reshape(arr,(1,6))

array([[7, 3, 7, 1, 2, 8]])

*Se puede hacer un reshape como lo haría C.*

In [6]:
np.reshape(arr,(2,3), 'C')

array([[7, 3, 7],
       [1, 2, 8]])

*También se puede hacer reshape a como lo haría Fortran.*

In [7]:
np.reshape(arr,(2,3), 'F')

array([[7, 2, 1],
       [7, 3, 8]])

*Además, existe la opción de hacer reshape según como esté optimizado nuestro computador. En este caso es como en C.*

In [8]:
np.reshape(arr,(2,3), 'A')

array([[7, 3, 7],
       [1, 2, 8]])