In [1]:
import numpy as np

In [10]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [11]:
arr.dtype

dtype('int64')

In [5]:
arr = np.array([1,2,3,4,5,6], dtype='float64')
arr.dtype

dtype('float64')

In [6]:
arr = np.array([1,2,3,4,5,6], dtype='float64')
arr

array([1., 2., 3., 4., 5., 6.])

In [12]:
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr = arr.astype(np.float64)

In [13]:
arr = np.array([0,1,2,3,4,5,6])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True,  True,  True])

In [14]:
arr = np.array([0,1,2,3,4,5,6])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6'], dtype='|S21')

In [15]:
arr = np.array(['0','1','2','3','4','5','6'])
arr = arr.astype(np.int0)
arr

array([0, 1, 2, 3, 4, 5, 6])

In [16]:
arr = np.array(['0','1','2','3','4','5','6'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4, 5, 6], dtype=int8)